### ISSUE TITLE
[Suggestion] Use Tags in addition to items names in Config

### ISSUE THREAD

**Issue by 8Mobius8** [GekidoLukas/weaponleveling#33]
**Describe your Suggestion**
Was trying to setup this mod to only include armor leveling and/or specific weapons to use level mod but as a modpack creator it's pretty tedious and difficult to list all the different items I want to use Weapons Leveling.

It would be great, if we could use minecraft's tagging system to include and exclude items to be used in Leveling.

For instance imagine  in the server config:
```toml
[server.item]
    blacklist_items = ["#unsupported_mod:metal_swords"]

[server.entiy]
   monster_entities = ["#stalwart_dungeons:monsters", ...]
```

Supporting tags in general would make integration with other mods much easier and configuration of the many types of weapons and mobs in various modpacks much easier.

Modpack creators could create tags if they don't already exist and include them in the WeaponsLeveling configuration for their worlds.

**Additional context**
Attempted to use tags in configuration but doesn't seem to work.
